[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5
  
[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

